version: "3.7"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - "80:80"        # web
      - "443:443"      # web
      - "8888:8888"    # Admin Watcher Port
      - "9999:9999"    # Storefront Watcher Port
      - "9998:9998"    # Storefront Watcher Port
    environment:
      - CADDY_INGRESS_NETWORKS=web
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped
  socks:
    image: serjs/go-socks5-proxy
    ports:
      - "1080:1080"
    networks:
      - web
    restart: unless-stopped
networks:
  web:
    external: true

volumes:
  caddy_data: { }